// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b8hRtVZwnsxZ7ZEtnDCx5m
// Component: vPGSXFymdT
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project_mobile_first.module.css"; // plasmic-import: b8hRtVZwnsxZ7ZEtnDCx5m/projectcss
import sty from "./PlasmicTodo.module.css"; // plasmic-import: vPGSXFymdT/css

import SvgonClickremoveIcon from "./icons/PlasmicIcon__SvgonClickremove"; // plasmic-import: TBk4gYtxT/icon

export type PlasmicTodo__VariantMembers = {};

export type PlasmicTodo__VariantsArgs = {};
type VariantPropType = keyof PlasmicTodo__VariantsArgs;
export const PlasmicTodo__VariantProps = new Array<VariantPropType>();

export type PlasmicTodo__ArgsType = {};
type ArgPropType = keyof PlasmicTodo__ArgsType;
export const PlasmicTodo__ArgProps = new Array<ArgPropType>();

export type PlasmicTodo__OverridesType = {
  root?: p.Flex<"div">;
  textcontent2?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
};

export interface DefaultTodoProps {
  className?: string;
}

function PlasmicTodo__RenderFunc(props: {
  variants: PlasmicTodo__VariantsArgs;
  args: PlasmicTodo__ArgsType;
  overrides: PlasmicTodo__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"textcontent2"}
        data-plasmic-override={overrides.textcontent2}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.textcontent2
        )}
      >
        {"deploy figlit description"}
      </div>

      <SvgonClickremoveIcon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "textcontent2", "svg"],
  textcontent2: ["textcontent2"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  textcontent2: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTodo__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTodo__VariantsArgs;
    args?: PlasmicTodo__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTodo__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTodo__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTodo__ArgProps,
      internalVariantPropNames: PlasmicTodo__VariantProps
    });

    return PlasmicTodo__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTodo";
  } else {
    func.displayName = `PlasmicTodo.${nodeName}`;
  }
  return func;
}

export const PlasmicTodo = Object.assign(
  // Top-level PlasmicTodo renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textcontent2: makeNodeComponent("textcontent2"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicTodo
    internalVariantProps: PlasmicTodo__VariantProps,
    internalArgProps: PlasmicTodo__ArgProps
  }
);

export default PlasmicTodo;
/* prettier-ignore-end */
